language: php

php:
  - 5.4

services: memcache

env:
  global:
    - MEMCACHED__HOST=localhost
    - PHPCS_VERSION='1.5.5'
    - CODER_VERSION='dev-7.x-2.x'

branches:
  except:
    - 7.x-1.x

mysql:
  database: drupal
  username: root
  encoding: utf8

matrix:
  fast_finish: true

before_install:
  - sudo apt-get update > /dev/null
  # Always update Composer to the recent version, otherwise the drush
  # installation fails.
  - composer selfupdate

install:
  - sudo apt-get update > /dev/null
  - "mysql -e 'create database drupal;'"

  # Install compass
  - gem install sass -v 3.2.19
  - gem install compass -v 0.12.6
  - gem install susy -v 1.0.9

  # Install latest Drush 6.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction --prefer-source drush/drush:6.*
  - drush dl -y drupalorg_drush-7.x-1.x-dev --destination=$HOME/.drush
  - drush cc drush

  # install php code sniffer globally
  - composer global require squizlabs/php_codesniffer:$PHPCS_VERSION
  - composer global require drupal/coder:$CODER_VERSION

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install --no-interaction --prefer-source
  - cd ../../../

  # Setting Behat environment
  - DISTRO=`echo $TRAVIS_BUILD_DIR | sed -e "s/\/[^\/]*$//"`
  - export BEHAT_PARAMS="extensions[Drupal\\DrupalExtension\\Extension][drupal][drupal_root]=$DISTRO/drupal"

  # Create a Drupal coding standard reference in PHPCS coding standards.
  - ln -s ~/.composer/vendor/drupal/coder/coder_sniffer/Drupal ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/Standards

  # Run the Coder sniffer before all heavy tasks.
  - phpcs --report=full --standard=Drupal --extensions=php,inc,module,install $TRAVIS_BUILD_DIR/modules/custom $TRAVIS_BUILD_DIR/themes/city_of_malmo/template.php

  # Build Codebase
  - mkdir private_files
  - mkdir profiles
  - mv $TRAVIS_BUILD_DIR profiles/mal
  - mkdir drupal
  - mv profiles drupal/

  # Build the current branch
  - cd drupal
  - drush make --yes profiles/mal/drupal-org.make --contrib-destination=profiles/mal --no-cache
  - cd ../

  # Setup files
  - sudo chmod -R 777 drupal/sites/all

  # Setup display for Selenium
  - export DISPLAY=:99.0
  - cat /etc/init.d/xvfb
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.42/selenium-server-standalone-2.42.1.jar
  - java -jar selenium-server-standalone-2.42.1.jar > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '4444.*LISTEN'; do true; done

   # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo 'extension = "memcache.so"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

before_script:
  # Do the site install (either the current revision or old for the upgrade).
  - cd drupal
  - drush si mal --db-url=mysql://root:@127.0.0.1/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Vuxenutbildning Malmö" --yes

  - cd ..
  - curl -sSL https://raw.githubusercontent.com/moliware/travis-solr/master/travis-solr.sh | SOLR_VERSION=4.4.0 SOLR_CONFS="drupal/profiles/mal/solr-conf"  bash

  - cd drupal/profiles/mal

  - export SEARCH_API_PATH="\"/solr/core0\""
  - export SEARCH_API_PORT="\"8983\""
  - sh scripts/after_install.sh

  - cd ../../
  - pwd
  # Start server
  - drush runserver --server=builtin 8888 > /dev/null 2>&1 &
  - until netstat -an 2>/dev/null | grep '8888.*LISTEN'; do true; done
  - cd profiles/mal/tests/behat

script:

  - ./bin/behat --config behat.travis.yml

notifications:

  irc: "chat.freenode.net#drupal-propeople-mal"
